### ISSUE TITLE
Custom directive not working

### ISSUE THREAD

**Issue by mattzahel** [oliverfindl/vue-svg-inline-plugin#12]
During the migration of my Vue 3 app from Webpack to Vite, I decided to switch from https://github.com/oliverfindl/vue-svg-inline-loader to this plugin, as it was recommended in README. Unfortunately, I had to rename all directive usages from `svg-inline` to `v-svg-inline`, because the custom directive simply doesn't work.

Reproduction link: https://codesandbox.io/s/relaxed-mendel-98zk3y

Am I missing something or this is a bug?

**Comment by oliverfindl** [comment]
Hello,

this plugin uses by default `v-svg-inline` directive name. You could change it according to [plugin options](https://github.com/oliverfindl/vue-svg-inline-plugin#configuration), but [Vue](https://github.com/vuejs/vue-next) will automatically register it with `v-` prefix anyway. Because of this convention ([Vue](https://github.com/vuejs/vue-next) directives always starting with `v-` prefix), this plugin is not drop-in replacement for [vue-svg-inline-loader](https://github.com/oliverfindl/vue-svg-inline-loader). In this case, It was my fault when I initially created [vue-svg-inline-loader](https://github.com/oliverfindl/vue-svg-inline-loader) without `v-` prefix for directive name, because it was iteration of another (not-[Vue](https://github.com/vuejs/vue-next) related) project.

If you have more questions, feel free to ask here.

Thanks.

**Comment by mattzahel** [comment]
That makes sense, thanks a lot for your explanation @oliverfindl!
