### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by markusand** [oliverfindl/vue-svg-inline-plugin#14]
I'm not an expert, I'm sorry if I'm wrong with my assumptions. Vue instance is injected in install method and Axios instance is passed in options object or taken from global scope. Would setting Vue and Axios as peerDependencies help reduce the size of the bundle?

**Comment by oliverfindl** [comment]
Hello,

well, I can set them as `peerDependencies`, but it won't solve your issue with bundle size, because this plugin is not using them at all.

https://github.com/oliverfindl/vue-svg-inline-plugin/blob/63566067340121503b46a6d66faac4be3742487a/package.json#L47-L51

Large bundle size is because of 2 things:
- transpilation for older browsers (`core-js`),
- polyfills for older browsers (`intersection-observer` and `whatwg-fetch`).

If you are using this plugin directly in browser (e.g.: via CDN), you can use [modern version](https://github.com/oliverfindl/vue-svg-inline-plugin/blob/master/dist/vue-svg-inline-plugin-modern.min.js) (`-modern` suffix in filename), which has no transpilation and no polyfills in place. 

If you are using bundler, it's up to you to transpile it and include polyfills according your own needs.

If you have more questions, feel free to ask here.

Thanks.
