### ISSUE TITLE
Image cached?

### ISSUE THREAD

**Issue by tomastan** [oliverfindl/vue-svg-inline-plugin#17]
It looks that the plugin caches the SVG file before importing. So if the file is changed, I still see old file inline. As a workaround I had to add "?.." in the URL. 

So does the cache really exist? And how to flush it on source image change?

**Comment by tomastan** [comment]
Unfortunately the workaround is not good. We have different git branches with different SVG images and the same Vue source code. So switching to between branches keeps the image from the initial branch instead of the correct one from the branch checked out.

**Comment by oliverfindl** [comment]
Hello,

please do as follows:
- open [readme](https://github.com/oliverfindl/vue-svg-inline-plugin/blob/master/README.md) for this project,
- press ctrl + f,
- type cache,
- press enter few times,
- check `cache.presistent` option.

I was gonna disable this feature in February, because of legislation changes in my country (cannot access user storage without user consent), but I totally forgot about it.

I will update this package in few days.

Thanks.

**Comment by tomastan** [comment]
Hi @oliverfindl,

Good sarcasm ;). It was not clear what localCache has in common with the build process, so I skipped that first. It helped after all. Hence the cache looks to be still not flushed, as if I restore `cache.persistent` setting back, I get old cached file. But if you going to remove this setting anyway, this issue may be irrelevant.

Thanks for the support
