### ISSUE TITLE
Usage configuration

### ISSUE THREAD

**Issue by wng97** [oliverfindl/vue-svg-inline-plugin#6]
@oliverfindl Hi Oliver, may I know where should I place the Webpack configuration in, if i am building a vue2 with quasar project? should I create a new boot file and name it as any name?

**Comment by oliverfindl** [comment]
Hello,

unfortunately, I'm not familiar with [Quasar](https://github.com/quasarframework/quasar). Don't know if you made mistake about submitting issue to different repo, but this plugin doesn't require any interaction with [Webpack](https://github.com/webpack/webpack). If you had in mind [plugin configuration](https://github.com/oliverfindl/vue-svg-inline-plugin#configuration) instead of [Webpack](https://github.com/webpack/webpack) configuration, that should be placed before [Vue](https://github.com/vuejs/vue) mounting to DOM. As for [Quasar](https://github.com/quasarframework/quasar), I didn't test it, but from brief look at it, it should be similar to as [vue-i18n example](https://quasar.dev/quasar-cli/boot-files#vue-i18n) from boot files (whatever they are...).

For more questions, please submit new issue to [Quasar](https://github.com/quasarframework/quasar) repo, as they created their own abstractions, that I'm not aware of.

Thanks.

**Comment by oliverfindl** [comment]
Closing this issue.
